services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # keeps container's node_modules, not host's
      
      #add backend volume later if you want to use backend in development
